### ISSUE TITLE
Error when trying to access isActive() method

### ISSUE THREAD

**Issue by victorighalo** [vanilophp/product#12]
I get this error when i try to access isActive() method.

Return value of Konekt\Concord\Proxies\EnumProxy::targetClass() must be of the type string, null returned

**Comment by fulopattila122** [comment]
How do you access the method? Do you use a custom model in your application? Do you use the component standalone or within the Vanilo Framework?

**Comment by victorighalo** [comment]
I used all approaches. Custom model, Vanillo model, standalone, framework, I downgraded, upgraded. Just same errors. On Aug 5, 2020 11:05 PM, Attila Fulop <notifications@github.com> wrote:
How do you access the method? Do you use a custom model in your application? Do you use the component standalone or within the Vanilo Framework?

**Comment by fulopattila122** [comment]
Can you access other methods on the model? Did you customize the statuses of the product?

**Comment by fulopattila122** [comment]
Also, which version of Vanilo are you using? 1.2?

**Comment by victorighalo** [comment]
> Can you access other methods on the model? Did you customize the statuses of the product?

Yes, i can access other methods; i don't think i customised statuses. Is that possible?

**Comment by victorighalo** [comment]
> Also, which version of Vanilo are you using? 1.2?

Yes, version 1.2. I also downgraded but the error remains.

**Comment by fulopattila122** [comment]
Yes, customizing of statuses is possible: https://vanilo.io/docs/1.2/enums#customizing-enums

Can you please post here the output of the command:

```bash
php artisan concord:enums
```

?

**Comment by victorighalo** [comment]
> Yes, customizing of statuses is possible: https://vanilo.io/docs/1.2/enums#customizing-enums
> 
> Can you please post here the output of the command:
> 
> ```shell
> php artisan concord:enums
> ```
> 
> ?

```
+------------------+-------------------------------------------+----------------------------------------+
| Shorthand        | Contract                                  | Concrete                               |
+------------------+-------------------------------------------+----------------------------------------+
| address_type     | Konekt\Address\Contracts\AddressType      | Konekt\Address\Models\AddressType      |
| cart_state       | Vanilo\Cart\Contracts\CartState           | Vanilo\Cart\Models\CartState           |
| customer_type    | Konekt\Customer\Contracts\CustomerType    | Konekt\Customer\Models\CustomerType    |
| gender           | Konekt\Address\Contracts\Gender           | Konekt\Address\Models\Gender           |
| gravatar_default | Konekt\AppShell\Contracts\GravatarDefault | Konekt\AppShell\Models\GravatarDefault |
| name_order       | Konekt\Address\Contracts\NameOrder        | Konekt\Address\Models\NameOrder        |
| province_type    | Konekt\Address\Contracts\ProvinceType     | Konekt\Address\Models\ProvinceType     |
| user_type        | Konekt\User\Contracts\UserType            | Konekt\User\Models\UserType            |
+------------------+-------------------------------------------+----------------------------------------+
```

**Comment by fulopattila122** [comment]
Product Status is missing as I expected. Can you post the contents of `config/concord.php`?

**Comment by victorighalo** [comment]
> Product Status is missing as I expected. Can you post the contents of `config/concord.php`?

```php
<?php

return [
    'modules' => [
        Konekt\AppShell\Providers\ModuleServiceProvider::class => [
            'ui' => [
                'name' => 'Vanilo',
                'url' => '/admin/product'
            ]
        ],
        Vanilo\Cart\Providers\ModuleServiceProvider::class
    ]
];

```

**Comment by fulopattila122** [comment]
The product module hasn't been added.

You have to add it:

```php
<?php

return [
    'modules' => [
        Konekt\AppShell\Providers\ModuleServiceProvider::class => [
            'ui' => [
                'name' => 'Vanilo',
                'url' => '/admin/product'
            ]
        ],
        Vanilo\Cart\Providers\ModuleServiceProvider::class,
        Vanilo\Product\Providers\ModuleServiceProvider::class // <- add this line
    ]
];
```

**Comment by victorighalo** [comment]
> The product module hasn't been added.
> 
> You have to add it:
> 
> ```
> <?php
> 
> return [
>     'modules' => [
>         Konekt\AppShell\Providers\ModuleServiceProvider::class => [
>             'ui' => [
>                 'name' => 'Vanilo',
>                 'url' => '/admin/product'
>             ]
>         ],
>         Vanilo\Cart\Providers\ModuleServiceProvider::class,
>         Vanilo\Product\Providers\ModuleServiceProvider::class // <- add this line
>     ]
> ];
> ```

thanks... it works now. btw: why wasn't it there? did i miss something in the docs? is this necessary when using the standalone products module?

**Comment by victorighalo** [comment]
I also get the same error when i do this: $taxon->taxonomy. So i added:         

```
Vanilo\Category\Providers\ModuleServiceProvider::class,
Vanilo\Properties\Providers\ModuleServiceProvider::class,
```

_Can these be automatically discovered by the package?_

**Comment by fulopattila122** [comment]
Add `Vanilo\Category\Providers\ModuleServiceProvider::class` to `concord.php`.
Basically, every Vanilo module must be added this way.

Concord v2.0 will be hooked with auto-discovery, currently, you have to do this. It's a one-time 5-second change ;)

**Comment by victorighalo** [comment]
> Add `Vanilo\Category\Providers\ModuleServiceProvider::class` to `concord.php`.
> Basically, every Vanilo module must be added this way.
> 
> Concord v2.0 will be hooked with auto-discovery, currently, you have to do this. It's a one-time 5-second change ;)

Thanks. Issues with concord resolved.
