### ISSUE TITLE
Class App\Product must extend or implement Vanilo\Category\Contracts\Taxon.

### ISSUE THREAD

**Issue by victorighalo** [vanilophp/product#13]
I get this exception when i create a custom model for both Taxon and Product:

`Class App\Product must extend or implement Vanilo\Category\Contracts\Taxon.`

When i implement Taxon, then i'm forced to also add the method definitions of the Taxon interface.

**Comment by fulopattila122** [comment]
`Product` must obviously not implement the Taxon interface.
How do you set up the custom models?

**Comment by victorighalo** [comment]
> `Product` must obviously not implement the Taxon interface.
> How do you set up the custom models?

```php
        $this->app->concord->registerModel(TaxonContract::class, \App\Product::class);
        $this->app->concord->registerModel(TaxonContract::class, \App\Taxon::class);
```

**Comment by fulopattila122** [comment]
Do I have to explain? :)

```php
$this->app->concord->registerModel(ProductContract::class, \App\Product::class);
$this->app->concord->registerModel(TaxonContract::class, \App\Taxon::class);
```
