### ISSUE TITLE
Sluggable package is not being installed

### ISSUE THREAD

**Issue by ganyicz** [vanilophp/product#14]
When installing as a standalone module the Sluggable package is not being installed

`PHP Fatal error:  Trait 'Cviebrock\EloquentSluggable\Sluggable' not found in /vendor/vanilo/product/src/Models/Product.php on line 20`

Steps to reproduce:

1. Install new Laravel app
2. Install Product package
3. Run the app

Vanilo\Product 2.0.0
Laravel 8.15.0
Composer 2.0.0

**Comment by fulopattila122** [comment]
Thanks for the report! It's been fixed and released in `v2.0.1`
