### ISSUE TITLE
No SKU

### ISSUE THREAD

**Issue by Payetus** [vanilophp/product#2]
There is no SKU stock keeping unit. The number of stock left for each product of option (Examples: size, color, type, material... )

**Comment by fulopattila122** [comment]
Product attributes/options don't yet exist as of Vanilo v0.4.
This feature is the main target for v0.5: https://vanilo.io/docs/0.4/roadmap

**Comment by fulopattila122** [comment]
Could you please elaborate what/how exactly you'd like to be implemented?
