### ISSUE TITLE
No Quantity

### ISSUE THREAD

**Issue by victorighalo** [vanilophp/product#4]
In my project i have gotten to a point where i need to add product quantity and then i realised there is not quantity column on the table. So is there a better way to set and get product quantity or to add my own migration to update the product table.

**Comment by fulopattila122** [comment]
Do you mean quantity unit like "kg" "pcs" or quantity like stock?

**Comment by victorighalo** [comment]
> Do you mean quantity unit like "kg" "pcs" or quantity like stock?

Quantity like available stock I mean.

**Comment by fulopattila122** [comment]
This simple stock feature is just about to be added: https://vanilo.io/docs/master/roadmap
The field name will be highly likely `stock`, and supporting features like `$product->isOnStock()` and/or `$product->isAvailable()` and/or `$product->canBeBought()` will be added.

How urgent is it for you, how many days can you wait for it?

**Comment by victorighalo** [comment]
> This simple stock feature is just about to be added: https://vanilo.io/docs/master/roadmap
> The field name will be highly likely `stock`, and supporting features like `$product->isOnStock()` and/or `$product->isAvailable()` and/or `$product->canBeBought()` will be added.
> 
> How urgent is it for you, how many days can you wait for it?

Nice! It's a crucial part of the project but i guess I can wait for it for one-two weeks while I work on other parts of my project.

**Comment by fulopattila122** [comment]
Good, it'll take about that. I'll keep you updated within this Issue.
