### ISSUE TITLE
Add multiple property values to product

### ISSUE THREAD

**Issue by Romik90** [vanilophp/product#6]
Is it possible to add more than one property value to product? For instance let's assume that I have property Materials, and product could be made of many materials

**Comment by fulopattila122** [comment]
At the moment it's not possible.

There were already discussions about this topic and it's very probable that it'll be possible in one of the upcoming releases, but it's not scheduled at the moment.

**Comment by Romik90** [comment]
Ok. One more question: are you gonna implement the product variations? For example one product could be in different colours, different sizes, and each variant have its own price

**Comment by fulopattila122** [comment]
Yes. This is planned for v1.2 https://vanilo.io/docs/0.5/roadmap#12-diversity
