### ISSUE TITLE
How to paginate productFinder results?

### ISSUE THREAD

**Issue by Romik90** [vanilophp/product#7]
I couldn't find a way how to properly paginate productFinder results with standart laravel method

**Comment by yusufkandemir** [comment]
Firstly, I think I understand your problem but please be more expressive when describing problems.

I need to say that the [ProductFinder](https://github.com/vanilophp/framework/blob/3b0c17c55b3ae38768ef9f52d92fe294e4060313/src/Search/ProductFinder.php) is in scope of [vanilophp/framework](https://github.com/vanilophp/framework), so it would be better to open the issue there. And it is just a pretty wrapper for _Laravel Query Builder_. So this

```php
$finder = new ProductFinder();
$results = $finder->havingPropertyValue($propertyValue)->withinTaxon($taxon)->getResults();
```

is same as this.

```php
$results = Product::whereHas('propertyValues', function ($query) use ($propertyValue) {
            $query->where('id', $propertyValue->id);
        })->whereHas('taxons', function ($query) use ($taxon) {
            $query->where('id', $taxon->id);
        })->get();
```

So `$results` will be a Laravel Collection. As there is no method to paginate data or expose internal `Query Builder`, you can't paginate unfortunately. But I think we need to add such feature. I'll try to implement that and send a PR.
