### ISSUE TITLE
Create product variants

### ISSUE THREAD

**Issue by Romik90** [vanilophp/product#8]
Are you gonna implement the product variations? For example one product could be in different colours, different sizes, and each variant have its own price

**Comment by yusufkandemir** [comment]
Product variations is on [roadmap](https://vanilo.io/docs/0.5/roadmap#12-diversity). If plans go well, it will be implemented in v1.2 on July 2019.

**Comment by yusufkandemir** [comment]
You also asked this on another [issue](https://github.com/vanilophp/product/issues/6) as a [comment](https://github.com/vanilophp/product/issues/6#issuecomment-487386738)
> Ok. One more question: are you gonna implement the product variations? For example one product could be in different colours, different sizes, and each variant have its own price

And got this [reply](https://github.com/vanilophp/product/issues/6#issuecomment-493559729)
> Yes. This is planned for v1.2 https://vanilo.io/docs/0.5/roadmap#12-diversity

**Comment by Romik90** [comment]
Cool

**Comment by reimo** [comment]
Hello guys the deadline for 1.2 has passed
https://vanilo.io/docs/0.5/roadmap#12-diversity

What is the process, I will like to know so I can decide either to start working on product variants

**Comment by fulopattila122** [comment]
@reimo we're still stabilizing v1.0 thus the "Diversity" release has been rescheduled, please check the updated roadmap: https://vanilo.io/docs/0.5/roadmap#11-diversity

**Comment by atapatel** [comment]
Hi @fulopattila122 , any ball park date for when will product variant will be released?

**Comment by RekhaPatel6213** [comment]
Hello @fulopattila122, Any update of product variant feature? I am waiting for this feature.

**Comment by fulopattila122** [comment]
Now they are really coming in v3.0 that is coming in the next weeks: https://vanilo.io/docs/2.x/roadmap

Be aware that 3.0 will be PHP 8+ and Laravel 9+ only

Stay tuned :sunglasses:

**Comment by atapatel** [comment]
@fulopattila122 waiting for release!!

**Comment by fulopattila122** [comment]
> @fulopattila122 waiting for release!!

@atapatel Not earlier than Laravel 9 official release, which is 8th February at the moment: https://laravel-news.com/laravel-9

**Comment by atapatel** [comment]
@fulopattila122 🤞 for the newer version of vanilio e-commerce.

**Comment by fulopattila122** [comment]
Version 3 is to be released within a day.

See the documentation regarding product variants:

Product Variants overview: https://vanilo.io/docs/master/product-variants
The links-based approach: https://vanilo.io/docs/master/links (already implemented part of 3.0)
Master<->Variant approach: https://vanilo.io/docs/master/master-products (incomplete, part of 3.1 - March)

**Comment by bloomlive** [comment]
@fulopattila122, you mentioned 3.1 being released in March. How is it going? Do you guys need help?
